### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by 2inqui** [open-pay/openpay-swift-ios#4]
Hello there. I was trying to integrate the SDK in my current project and I reading the doc says that I need to add a Headers Folder which I couldn't find anywhere in the project. It would be really helpful to have some assistance to integrate the sdk since Im unable to continue with the integration.

Can we be more specific about what [Headers](https://github.com/open-pay/openpay-swift-ios#includes-folder) is and where to find them?

I think this documentation was based on the other [project](https://github.com/open-pay/openpay-ios)

**Comment by igrijalva** [comment]
The easiest way to implement the framework is to download the precompiled package from the following link: [Download the pre-built framework](https://github.com/open-pay/openpay-swift-ios/releases) And drag it (Openpay.framework) into your project

![importframework](https://cloud.githubusercontent.com/assets/23488784/25291560/275cdab8-2698-11e7-8271-fb2345e48ea2.gif)

Be sure to include it in Embeded Binaries and continue with the steps described in the [Usage](https://github.com/open-pay/openpay-swift-ios#usage) section.

The other way is similar but instead of downloading the precompiled framework, you must download the source code and compile it yourself.

**Comment by cesarmtz93** [comment]
@igrijalva it still doesn´t work

**Comment by igrijalva** [comment]
Hi Cesar,
Can you give me more information about your problem please

@cesarmtz93

**Comment by cesarmtz93** [comment]
@igrijalva Hi sure, so I'm trying to migrate the library from the objective-c one to this one, but i have imported the prebuilt framework into the project binaries, but it still doesn't get recognized and i cannot instantiate the variable of the openpay object.

**Comment by igrijalva** [comment]
@cesarmtz93 Just to confirm, are you migrating your Objective-C code to Swift? Or Is your code maintained in Objective-C?

**Comment by cesarmtz93** [comment]
@igrijalva my code is in swift but i've been using the openpay objective c library but like i said i want to use the swift library, also the main problem that i have is that the objective c library something it lets me add a new card but other times it doesnt

**Comment by igrijalva** [comment]
@cesarmtz93 

What version of Swift are you using? this pre-built is compiled in 3.0.2

**Comment by cesarmtz93** [comment]
@igrijalva  Swift version 3.1

**Comment by igrijalva** [comment]
I was able to reproduce the error with version 3.1. 
![image](https://cloud.githubusercontent.com/assets/23488784/26174547/5b32868a-3b15-11e7-884d-9ec8fc62107c.png)
![image](https://cloud.githubusercontent.com/assets/23488784/26174673/c628cdc8-3b15-11e7-828b-9de55e75a09f.png)

The recommendation is that you download the source code and integrate it as a dependency to your project so that it is compiled with the same version

**Comment by cesarmtz93** [comment]
@igrijalva which files do i need to include?

**Comment by 2inqui** [comment]
@cesarmtz93 FYI I ended up using the [Objective-c](https://github.com/open-pay/openpay-ios) version, I didn't have any issue to integrate it.

**Comment by cesarmtz93** [comment]
@2inqui thanks you, are you having issues when creating a token? 

`        openPayAPI?.createToken(with: OPCard!, success: { (OPToken?) in
            <#code#>
        }, failure: { (Error?) in
            <#code#>
        })`

**Comment by 2inqui** [comment]
No. but I haven't checked it recently.

**Comment by igrijalva** [comment]
It is very simple, you just have to drag the file "Openpay.xcodeproj" to your project inside the "Navigator" of "Xcode". Subsequently adds the framework in "Embedded Binaries" and "Linked Frameworks and Libraries" within the configuration of TARGETS


![importswiftprojectframework](https://cloud.githubusercontent.com/assets/23488784/26179319/a41336c0-3b28-11e7-8139-e37a25d97308.gif)


@cesarmtz93 @2inqui

**Comment by igrijalva** [comment]
@2inqui I invite you to try with this way of implementation, once you adapt to the operation of Swift is much simpler than Objective-C

**Comment by cesarmtz93** [comment]
@igrijalva my obj c library was working fine but the problem that i'm encountering is with the method i wrote above it not generating the tokin and i need it for my request to my server
